[package]
name = "venice"
license = "MPL-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
micropython-rs.path = "../micropython-rs"
cty = "0.2.2"
bitflags = "2.9.2"
paste = "1.0.15"
vex-sdk = "0.28.0"
vexide-devices = { git = "https://github.com/vexide/vexide" }
rgb = "0.8.52"
vex-sdk-jumptable = "0.1.1"
talc = "4.4.3"
thiserror = "2.0.17"

[build-dependencies]
cc = "1.2.49"
regex = "1.11.1"
format-bytes = "0.3.0"

[dependencies.venice-program-table]
git = "https://github.com/venice-v5/venice-program-table"
rev = "ec40504b24b0adcf3b15c06e7fd403fdcdfd71c8"
features = ["builder"]
