[package]
name = "venice"
license = "MPL-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
venice-program-table = { git = "https://github.com/venice-v5/venice-program-table.git", rev = "e5a1762be2eeaf94841bb972af4e447bbf5f4eea" }
micropython-rs.path = "../micropython-rs"
vex-registry.path = "../registry"
cty = "0.2.2"
bitflags = "2.9.2"
paste = "1.0.15"
vex-sdk = "0.27.1"
vexide-devices = "0.7.0"

[build-dependencies]
format-bytes = "0.3.0"
regex = "1.11.1"
vex-sdk-vexcode = "0.0.1"
